site_name: Client Léger Debian
site_description: Documentation pour configurer un client léger Debian en ligne de commande
site_author: Leonard Bonnet

theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.svg  # facultatif : remplace par ton logo
  favicon: assets/favicon.ico  # facultatif
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - header.autohide

nav:
  - Accueil: index.md
  - Installation:
      - Mise à jour: installation
      - Paquets essentiels: installation
  - Configuration:
      - Session légère: configuration
  - Sécurité: 
      - droit: securite
      - ACL: securite
  - Utilisation:
      - Prise en main: utilisation
      - Avancée: utilisation
  - Ressources: resources

plugins:
  - search

extra_css:
  - stylesheets/custom.css

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
