

site_name: Client Léger Debian
site_description: Documentation pour configurer un client léger Debian en ligne de commande
site_author: Leonard Bonnet
site_url: https://github.com/psfr0ad/doc-clientleger-nimrodmkdocs gh-deploy

theme:
  name: material
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Accueil: index.md
  - Installation:
      - Mise à jour: docs/install_update.md
      - Paquets essentiels: docs/install_packages.md
  - Configuration:
      - Session légère: docs/config_session.md
  - Ressources: docs/resources.md

plugins:
  - search

extra_css:
  - stylesheets/custom.css

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

