

site_name: Client Léger Debian
site_description: Documentation pour configurer un client léger Debian en ligne de commande
site_author: Leonard Bonnet


theme:
  name: material
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Accueil: index.md
  - Installation:
      - Mise à jour: installation
      - Paquets essentiels: installation
  - Configuration:
      - Session légère: configuration
  - Sécurité: 
      - droit: securite
      - ACL: securite
  - Utilisation:
      - Prise en main: utilisation
      - Avancée: utilisation
  - Ressources: resources

plugins:
  - search

extra_css:
  - stylesheets/custom.css

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

